### ISSUE TITLE
vlc(shell) support

### ISSUE THREAD

**Issue by crawlersick** [m13253/danmaku2ass#18]
其实网络功能简单用shell就可以实现了。附上vlc 的shell . 对应该一下这几行命令就可以满足不同的需求。
https://github.com/crawlersick/danmaku2ass/blob/master/bili2any

**Comment by m13253** [comment]
渣浪和优酷的多分段视频能支持么？

**Comment by crawlersick** [comment]
不能 ～。～ 目前只是优先解决我要看的视频后续再更新。我只是觉得网络一块用shell写对Linux用户自由度更大。
於 2015年3月23日 下午12:27，"Star Brilliant" <notifications@github.com> 寫道：

**Comment by m13253** [comment]
如果你需要方便的观看功能的话，可以使用 Danmaku2ASS 的某个前端 [BiliDan](https://github.com/m13253/BiliDan)。
