### ISSUE TITLE
Wrong zh_TW translation of "default"

### ISSUE THREAD

**Issue by 910JQK** [m13253/danmaku2ass#19]
in <code>locale/zh_TW/LC_MESSAGES/danmaku2ass.po</code>:
「默認」 -> 「預設」

Reference:
https://www.moedict.tw/~%E9%A0%90%E8%A8%AD

**Comment by m13253** [comment]
谢谢你的指导。

能麻烦你修复翻译，生成正确的 .mo 文件然后 PR 给我吗？
谢谢。
