### ISSUE TITLE
我把这个项目集成到MoonPlayer里了

### ISSUE THREAD

**Issue by coslyk** [m13253/danmaku2ass#22]
https://github.com/coslyk/moonplayer 新版使用了这个项目提供弹幕支持

**Comment by m13253** [comment]
非常欢迎。
B站的视频 URL 获取，我这边有一个不错的方案 http://github.com/m13253/BiliDan 你可以借鉴。
希望我们互相共享成果。

**Comment by m13253** [comment]
我在 5a3fb6441a88f85e60032189df16cfda06dde831 中加入了 MoonPlayer 的推荐。
