### ISSUE TITLE
转换的字幕文件开头多出一空行导致新版mpv无法读取

### ISSUE THREAD

**Issue by guopm** [m13253/danmaku2ass#26]
详情见这边的issue：[It fails to load subtitle on occasion(https://github.com/mpv-player/mpv/issues/2506)](https://github.com/mpv-player/mpv/issues/2506)
作者说新版mpv换成用ffmpeg读字幕所以danmuku2ass转换的弹幕直接挂了
虽然改一点点源代码就好，但不得不说这ffmpeg真是够严格的= =

**Comment by m13253** [comment]
似乎是FFmpeg的文件类型猜测算法的锅。
如果你有精力就帮我改一下吧。

谢谢～

**Comment by m13253** [comment]
Fixed in #27
