### ISSUE TITLE
[功能需求]转换bilibili弹幕时似乎可以做到一些屏蔽选项

### ISSUE THREAD

**Issue by guopm** [m13253/danmaku2ass#28]
首先是关键字屏蔽，这个用正则匹配就好

顶部和底部的弹幕屏蔽可以匹配弹幕样式在转换的时候选择性的无视

深受广大补番爱好者喜爱的注册会员弹幕屏蔽似乎也可以做到，比如下面这个弹幕：

    <d p="763.19000244141,1,25,16777215,1447234124,0,D5790686,1338918387">看不懂啊</d>

倒数第二列以D开头的id都是注册会员的，虽然不一定准确，至少我用flash播放的时候他们都被屏蔽了

鄙人的python功底非常不行，所以只能死皮赖脸地来求新功能了T^T

**Comment by m13253** [comment]
好的。我记下了。
可惜我正在备考，所以短期内可能没精力写程序。
等我有空再考虑实现它吧。

谢谢～

**Comment by m13253** [comment]
Fixed in #38
