### ISSUE TITLE
麻烦各位帮忙阅读源代码找找可以优化的地方

### ISSUE THREAD

**Issue by m13253** [m13253/danmaku2ass#3]
今天发现此处可以做一些优化：
71776bacccf51d0dc3abec48143f02c6452d3f8f f27f9fe2590e4f3908bcf7500d09bf96a3bdc4bc

通过忽略重复的行可以节省约25倍计算量。

既然如此，源代码中可以优化或者有问题的地方应该很多。
如果你们有时间就帮助我找找这些地方吧。

希望不会占用各位太多时间。谢谢。

**Comment by zzjjbb** [comment]
https://github.com/m13253/danmaku2ass/blob/f71ef49f268dba519ef6155febed58762d086aee/danmaku2ass.py#L565
这一行好慢啊，虽然没仔细看逻辑，但是or后面改成5或10就快很多，副作用是行距变大了一点。
理论上能改成以字号为stepsize吗？如果逻辑上可行，我回头尝试改一下
测试了一个刚不到10万弹幕的例子，那个循环跑了3千万次，花了半分钟
