### ISSUE TITLE
ASS文件第一行为空

### ISSUE THREAD

**Issue by kasei-wang** [m13253/danmaku2ass#31]
WriteASSHead() 输出了一个空行，MPV无法打开字幕文件。
根据 [ASS规范](http://moodub.free.fr/video/ass-specs.doc) 第一行必须为 [Script Info] 。

**Comment by kasei-wang** [comment]
OK...抱歉，这个问题已经在 d97749af3f92c58bed45d4c0fec9a849c033de96 解决了。我使用的是ArchLinuxCN仓库中的旧版本。由于AUR未更新PKGBUILD，似乎lilacbot未被触发，导致了ArchLinuxCN仓库一直未更新。

**Comment by m13253** [comment]
好。解决了就好。
