### ISSUE TITLE
请教一下为什么我无法转换B站弹幕呢？提示：ValueError: Unknown comment file format

### ISSUE THREAD

**Issue by tea321000** [m13253/danmaku2ass#36]
以下命令行转换NICONICO弹幕可以正常完成，但是转换B站字幕时会报错，提示：ValueError: Unknown comment file format，请教一下这是为什么呢？以下是报错信息：
D:\danmaku2ass-master\danmaku2ass.py -o "1 (2).ass" -
s 1920x1080 -fn "微软雅黑" -fs 45 -a 0.8 -dm 5 -ds 5 "1 (2).xml"
Traceback (most recent call last):
File "D:\danmaku2ass-master\danmaku2ass.py", line 870, in le>
main()
File "D:\danmaku2ass-master\danmaku2ass.py", line 866, in main
Danmaku2ASS(args.file, args.output, width, height, args.protect, args.font,
args.fontsize, args.alpha, args.duration_marquee, args.duration_still, args.redu
ce)
File "D:\danmaku2ass-master\danmaku2ass.py", line 802, in Danma
ku2ASS
comments = ReadComments(input_files, font_size)
File "D:\danmaku2ass-master\danmaku2ass.py", line 831, in ReadC
omments
raise ValueError(_('Unknown comment file format: %s') % i)
ValueError: Unknown comment file format: 1 (2).xml

**Comment by m13253** [comment]
发一下弹幕出处吧。

这可能是 #24 老 bug。但是当年的代码太乱我也不知道怎么修了。

你试试吧 829 行：
```python
            CommentProcessor = GetCommentProcessor(f)
```
末尾加个 `or 'Bilibili'`，改成：
```python
            CommentProcessor = GetCommentProcessor(f) or 'Bilibili'
```

看看，这样识别不出来的文件就统统当 Bilibili 格式处理。

**Comment by tea321000** [comment]
原来如此，谢谢了，我还是用去BOM头工具好了，那样改代码不知道会不会引入新的BUG233
