### ISSUE TITLE
报Bug，转换后字幕顺序混乱

### ISSUE THREAD

**Issue by gonejack** [m13253/danmaku2ass#43]
视频与xml下载自```https://www.bilibili.com/bangumi/play/ss416```，转换后的ass大约在7分30秒钟左右，弹幕顺序出现大批混乱，原视频与原弹幕并无异常。本地播放器为IINA 0.0.15.1 build 69。

转换配置为
```
#!/bin/sh
block_list='(房价|我|别撸了|生日|生快|版权|盗版|屏蔽|地域|弹幕|举报|低龄|脑子|吃相|字幕|跳过|跳不了|什么玩意|乱七八糟|快进|什么鬼|水了|跳了|无力吐槽|食用|快乐|百度)'

for file in "$@"
do
  echo $file
  echo ${file%%.xml}.ass
  danmaku2ass -s 1920x1080 -a 0.90 -fn 苹方 -fs 36 -dm 15 -ds 10 -fl "$block_list" -o "${file%%.xml}.ass" "$file"
done
```

[av510431_我的朋友很少NEXT：第11话_迷茫而又懦弱的我.zip](https://github.com/m13253/danmaku2ass/files/2001120/av510431_.NEXT.11._.zip)

**Comment by m13253** [comment]
谢谢你的汇报。十分感谢你附带了 reproducible files 给我。

Danmaku2ASS 的源代码已经年久失修，因此我可能需要一段时间来处理它。
不过近几天我抽不出时间来调查这个 bug，请你谅解。

我之后会在这里跟进这个 bug。

感谢你对 Danmaku2ASS 的关注和支持！

**Comment by gonejack** [comment]
对不起，我查验之后发现是视频来源不同造成的，程序没有BUG，谢谢作者。
