### ISSUE TITLE
bilibili PC端的xml格式弹幕文件更新成2.0了，貌似转不了ass

### ISSUE THREAD

**Issue by clostou** [m13253/danmaku2ass#49]
就是从Microsoft Store里面下载的哔哩哔哩动画，缓存的弹幕文件片段如下：
`<?xml version="2.0" encoding="UTF-8"?><i><oid>200140199</oid><d p="34656419668557827,0,61486,1,25,16777215,1593244049,0,3dbb2ac3">握草</d><d p="34754197277638663,0,59166,1,25,16777215,1593430545,0,9ee00804">哇!</d><d p="34756064507854853,0,85100,1,25,16777215,1593434107,0,f2d4d56d">花擦</d><d p="34756661216280581,0,68609,1,25,16777215,1593435245,0,da7c12b1">密恐噩梦</d><d p="34758278075908099,0,19419,1,25,16777215,1593438329,0,c01dcfe2">首页通知书</d><d p="34776859265728517,0,75319,1,25,16777215,1593473770,0,1b180964">在外扩过程中异丙醇挥发，溶剂只剩下水形成的吗</d><d p="34778872253251589,0,68856,1,25,16777215,1593477609,0,af464b21">哇啊</d><d p="34785012342063107,0,14962,1,25,16777215,1593489320,0,d4727c54">有人懂这个吗</d><d p="34785323440930819,0,64239,1,25,16777215,1593489914,0,607a790d">好看</d><d p="34785664146866183,0,68201,1,25,16777215,1593490563,0,d73392f">哇</d><d p="34785966402568199,0,31539,1,25,16777215,1593491140,0,933b2b85">酒精吧？</d><d p="34786043575664643,0,48120,1,25,16777215,1593491287,0,2eadee2e">中文太小了</d><d p="34786153443360771,0,35665,1,25,41194,1593491497,0,dd1ba50f">美国的外用&quot;酒精&quot;一般是异丙醇</d><d p="34786496944799747,0,66534,1,25,16777215,1593492152,0,308a8108">好美</d><d p="34786970322862087,0,143059,1,25,16777215,1593493055,0,481c1036">我明白了</d><d p="34787654679134211,0,152807,1,25,16777215,1593494360,0,520477ba">虽然不是很懂，但是无妨</d><d p="34787750865534981,0,74830,1,25,16777215,1593494544,0,90ed6922">!好看</d><d p="34788354776104967,0,27687,1,25,16777215,1593495695,0,eb298367">首页通知书</d><d p="34788375536861191,0,67266,1,25,16777215,1593495735,0,eb298367">有意思</d><d p="34788394940760071,0,104289,1,25,16777215,1593495772,0,eb298367">颜色很好看唉</d>
......`

会报错：“ValueError: Failed to detect comment file format: ......”
希望作者能抽出时间改进一下，感谢

**Comment by m13253** [comment]
感谢汇报。
不过这个项目已经 7 年了，我不再有精力维护它了。

我把 issue 开放在这里，如果有别人有兴趣解决这个问题的话，我会非常欢迎。
