### ISSUE TITLE
relicense to 0BSD

### ISSUE THREAD

**Issue by MrRawes** [m13253/danmaku2ass#52]
the reason for this is that the [youtube-dl](http://ytdl-org.github.io/youtube-dl/) fork [yt-dlp](https://github.com/yt-dlp/yt-dlp) could possibly include the code of this project in [yt-dlp](https://github.com/yt-dlp/yt-dlp)
my recomendation is to relicense this project under [0BSD](https://spdx.org/licenses/0BSD.html)

PS in order to do this you would have to ask EVERY contributors permission (that is [legally significant](https://www.gnu.org/prep/maintain/maintain.html#Legally-Significant)) to relicense this project to [0BSD](https://spdx.org/licenses/0BSD.html)

https://github.com/yt-dlp/yt-dlp/issues/367

**Comment by m13253** [comment]
I'm good with the proposal, but the code is fairly old and not maintained.
Furthermore, the algorithm is different from the official danmaku layout algorithm.
I would recommend doing some rewrite rather than use the old code.
