### ISSUE TITLE
Current comment file format probe algorithm is not robust

### ISSUE THREAD

**Issue by m13253** [m13253/danmaku2ass#9]
Currently, Danmaku2ASS probes comment file format by prefetching the first bytes.

However, this may fail because there may be some `<!-- XML comments -->` (#8) or the JSON object may be reordered.

I am considering a robust algorithm which look into the XML  or JSON format to figure out which file format is used.

**Comment by alexvong1995** [comment]
I have added 6 lines of if-else to support NicoFox because I am using it. Feel free to pull or not to. Thanks.

**Comment by m13253** [comment]
> I have added 5 lines of if-else to support NicoFox because I am using it. Feel free to pull or not to. Thanks.

Pulled. Thanks for your improvements.

Maybe I will do a complete refactor this summer, introducing a better algorithm at that time.
It's hard to say whether I will have time then. :smile:

**Comment by alexvong1995** [comment]
Maybe also doing a reformat if have time? The 79 column rule :P

**Comment by m13253** [comment]
> Maybe also doing a reformat if have time? The 79 column rule :P

Yeah. I can't even face the source code I have written before. So ugly.
I need some reformat this summer vacation.

**Comment by m13253** [comment]
Fixed in #38
